### ISSUE TITLE
env param doesn't handle characters that need shell escaping

### ISSUE THREAD

**Issue by rjewell** [devicecloud-dev/device-cloud-for-maestro#8]
When you populate `env` with a value that normally needs shell escaping, this can cause a variety of unexpected behavior when the final command is executed.   For example, with:
```
    env: |
      USERNAME=username
      PASSWORD=pass$word
```

because `$word` gets interpolated by the shell, you get a resulting command like: 
```
npx --yes @devicecloud.dev/dcd cloud --api-key *** --api-url https://api.devicecloud.dev/ --env USERNAME=username --env PASSWORD=pass --quiet
```

I suspect this might be a problem with any value in paramString.

**Comment by riglar** [comment]
Thanks for reporting @rjewell !

This should be fixed in 1.2.1

https://github.com/devicecloud-dev/device-cloud-for-maestro/releases/tag/v1.2.1

Please re-open if you encounter any issues
